import pandas as pd
from datetime import datetime

from demo_data import get_demo_orders, get_demo_stats, get_demo_suggestions, get_demo_contacts
from flask import Flask, render_template, request, redirect, url_for, session, flash
from datetime import datetime
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from threading import Thread
from functools import wraps

from db_helpers import (
    NewContactSubmission, 
    update_contact_status,
    NewSuggestion, 
    NewGuestbook, 
    GetGuestbook, 
    CheckAvailability, 
    NewOrder, 
    GetContactSubmissions, 
    GetSuggestions, 
    GetOrders, 
    GetRealOrders, 
    update_order_status,
    add_partnership_inquiry,
    get_all_partnership_inquiries,
    update_partnership_status,
    search_orders,
    update_order_tracking,
    NewWishlistItem,
    GetWishlist,
    update_wishlist_status,
    update_wishlist_notes,
    add_suggestion_to_wishlist,
    add_suggestion_to_wishlist_db,
    archive_suggestion_db,
    update_suggestion_status_db,
    delete_wishlist_item_db,
    archive_wishlist_item_db,
    submit_app_request,
    update_app_request_notes,
    update_app_request_status,
    get_all_app_requests,
    get_app_request_stats,
    archive_app_request_db,
    archive_order_db
)
app = Flask(__name__)

cat_messages = {
    "Home": "Welcome to MK's interactive portfolio!|I'm Niels - I'm even worse than Clippy!  And I'll be your tour guide!|If you click on 'SLEEP', I'll take a little nap until you need to wake me up|Click on the 'WELCOME' bubble to get started!",
    "Resume": "Hop in my time machine and let's dive into MK's past!|You can download a copy of MK's resume at the top of this page as a souvenir!|Be sure to click on the tiles under the summary to get the tea!",
    "Portfolio": "Here's some of MK's cool projects!|Look for the links to watch demo videos or check out repositories on GitHub!",
    "Art": "MK has many talents!|Click any image to zoom in!|This page is part of the interactive experience!|Click add-to-cart to test out the e-commerce functionality!",
    "Jewelry": "MK has many talents!|Click any image to zoom in!|This page is part of the interactive experience!|Click add-to-cart to test out the e-commerce functionality!",
    "Manifold": "Click on 'About' to learn more!|Try clicking on the shape and dragging it with your mouse|Use your scroll wheel to zoom in|Try moving the 'Density' slider!",
    "Blobs": "BLOBS!",
    "D20": "Click the button above or press the spacebar to roll the D20 dice!",
    "Partner": "If you're an Atlanta vendor, submit this form to team up with MK and carry her art at your next event!|This is not a demo! She actually wants to partner with you!",
    "GuestBook": "Post a comment on MK's guestbook to let her know you were here!",
    "ContactMe": "Want to send MK a message?|Fill out the form and I’ll let MK know!",
    "SuggestionsBox": "MK is always looking to improve!Have ideas to make this site even better?|Fill out the form and I’ll pass them along!|...As long as the suggestion isn't to get rid of me!",
    "AppRequests": "If you think this is site is cool, just wait until you create something together!|Fill out the form and I’ll get MK to follow up about your next project!",
    "Cart": "Your haul is waiting!",
    "Checkout": "Don't put in your real CC Info!|This is a part of the interactive experience|In other words, it's a demo|YOu can check the box if you would like to actually puchase the items in your cart!|otherwise, this is justa demo|Either way, don't put in your real CC info!",
    "OrderConfirmation": "You did it",
    "DemoDashboard": "Welcome to your new dashboard",
    "DemoOrders": "View, manage, and update orders here|This is part of the interactive experience|Try it out!",
    "DemoContacts": "This is where you can read all the submissions from the contact me page|This is part of the interactive experience!|Messages for this demo were generated by Claude|Click view message then mark the message as read",
    "DemoSuggestions": "This is where you can read all the submissions from the suggestions box|This is part of the interactive experience!|Suggestions for the demo were generated by Claude|Click view suggestion then mark it as read",
    "AdminDashboard": "You're the best",
    "AdminContacts": "You're so cool",
    "AdminPartners": "Don't forget to do that thing you were thinking about earlier",
    "AdminWishlist": "Because you don't already have enough wish lists"
    }

# ============================================ ENVIRONMENTAL VARIABLES ============================================
app.secret_key = os.environ.get("SECRET_KEY")  
SENDER_EMAIL = os.environ.get("SENDER_EMAIL")  
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD")  
RECEIVE_INBOX = os.environ.get("RECEIVE_EMAIL")
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD")

# ============================================ ADMIN DECORATOR ============================================
def AdminRequired(f): # REQUIRE ADMIN LOGIN FOR DASHBOARD
    @wraps(f)
    def Decorated(*args, **kwargs):
        if not session.get('admin_logged_in'):
            return redirect(url_for('admin_login'))
        return f(*args, **kwargs)
    return Decorated

# ============================================ EMAIL FUNCTIONS ============================================
def SendSMTP(message): # TRY 587 THEN 465
    try:
        server = smtplib.SMTP("smtp.gmail.com", 587, timeout=10)
        server.starttls()
        server.login(SENDER_EMAIL, EMAIL_PASSWORD)
        server.sendmail(message["From"], message["To"], message.as_string())
        server.quit()
        return True, None
    except Exception as e1:
        try:
            server = smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=10)
            server.login(SENDER_EMAIL, EMAIL_PASSWORD)
            server.sendmail(message["From"], message["To"], message.as_string())
            server.quit()
            return True, None
        except Exception as e2:
            return False, f"587 error: {e1}; 465 error: {e2}"

def SendEmail(UserInput):
    try:
        print(f"DEBUG: Starting email send for {UserInput.get('HumanName')}...")
        if not SENDER_EMAIL or not EMAIL_PASSWORD:
            raise RuntimeError("Email settings not configured")

        message = MIMEMultipart("alternative")
        subject = f"New Request from Portfolio: {UserInput.get('Request', 'Contact')}"
        message["Subject"] = subject
        message["From"] = SENDER_EMAIL
        message["To"] = RECEIVE_INBOX

        text = (
            f"New submission from your portfolio website!\n\n"
            f"Name: {UserInput.get('HumanName')}\n"
            f"Email: {UserInput.get('EmailAddy')}\n"
            f"Inquiry Type: {UserInput.get('Request')}\n"
            f"Product Request: {UserInput.get('ProductRequest') or 'N/A'}\n"
            f"App Request: {UserInput.get('AppRequest') or 'N/A'}\n"
            f"Message: {UserInput.get('message')}\n"
            f"Timestamp: {UserInput.get('timestamp')}\n"
        )
        part = MIMEText(text, "plain")
        message.attach(part)

        ok, err = SendSMTP(message)
        if ok:
            print(f"✅ Email sent successfully for {UserInput.get('HumanName')}")
        else:
            print(f"❌ Email Error: {err}")
    except Exception as e:
        print(f"❌ Email Error: {type(e).__name__}: {e}")

def SendOrderEmail(order_data):
    try:
        print("DEBUG: Starting order email send...")
        if not SENDER_EMAIL or not EMAIL_PASSWORD:
            raise RuntimeError("Email settings not configured")

        message = MIMEMultipart("alternative")
        message["Subject"] = f"{'REAL PURCHASE REQUEST' if order_data.get('real_purchase') else 'Demo Order'} from {order_data.get('name')}"
        message["From"] = SENDER_EMAIL
        message["To"] = RECEIVE_INBOX

        items_text = "\n".join([f"- {item['name']} (${item['price']:.2f})" for item in order_data.get("items", [])])
        purchase_status = "CUSTOMER WANTS TO ACTUALLY PURCHASE! Contact them to arrange payment." if order_data.get("real_purchase") else "This is a demo order - customer is just testing the site."

        text = (
            f"{'🚨 REAL PURCHASE REQUEST!' if order_data.get('real_purchase') else 'Demo Order Received'}\n\n"
            f"{purchase_status}\n\n"
            f"Order Number: {order_data.get('order_number')}\n\n"
            f"Customer Info:\nName: {order_data.get('name')}\nEmail: {order_data.get('email')}\nPhone: {order_data.get('phone')}\n\n"
            f"Shipping Address:\n{order_data.get('address')}\n{order_data.get('city')}, {order_data.get('state')} {order_data.get('zip')}\n\n"
            f"Order Details:\n{items_text}\n\n"
            f"Total: ${order_data.get('total', 0):.2f}\nOrder Date: {order_data.get('timestamp')}\n"
        )
        part = MIMEText(text, "plain")
        message.attach(part)

        ok, err = SendSMTP(message)
        if ok:
            print("✅ Order email sent successfully!")
        else:
            print(f"❌ Order Email Error: {err}")
    except Exception as e:
        print(f"❌ Order Email Error: {type(e).__name__}: {e}")

def EmailAsync(submission): # SEND EMAIL IN BACKGROUND THREAD
    thread = Thread(target=SendEmail, args=(submission,))
    thread.daemon = True
    thread.start()

def OrderEmailAsync(order_data): # SEND ORDER CONFIRMATION EMAIL IN BACKGROUND THREAD
    thread = Thread(target=SendOrderEmail, args=(order_data,))
    thread.daemon = True
    thread.start()

#============================================ PUBLIC PAGE ROUTES ============================================
@app.route("/")
def home(): # ABOUT PAGE
    return render_template("about.html", cat_message=cat_messages["Home"])

# ============================================  PORTFOLIO ============================================
@app.route("/resume")
def resume():
    return render_template("resume.html", cat_message=cat_messages["Resume"])

@app.route("/coding")
def coding():
    return render_template("coding.html", cat_message=cat_messages["Portfolio"])

# ============================================  INTERACTIVE EXPERIENCES ============================================
# ========== SIMPLE ROUTES
@app.route("/guestbook", methods=["GET", "POST"]) # GUESTBOOK
def guestbook():
    if request.method == "POST":
        new_entry = {
            "name": request.form.get("name", "Anonymous"),
            "message": request.form.get("message")
        }
        
        if NewGuestbook(new_entry):
            return redirect(url_for("guestbook"))
        else:
            return "Error saving guestbook entry", 500

    entries = GetGuestbook() # GET ENTRIES FROM POSTGRESQL
    
    comments = [] # CONVERT TO FORMAT EXPECTED BY TEMPLATE
    for entry in entries:
        comments.append({
            "name": entry['name'],
            "message": entry['message'],
            "timestamp": entry['posted_at'].strftime("%Y-%m-%d %H:%M:%S")
        })
    
    return render_template("guestbook.html", comments=comments, cat_message=cat_messages["GuestBook"])

@app.route("/CATastrophe")
def CATastrophe():
    return render_template("CATastrophe.html")

@app.route('/manifold')
def manifold():
    return render_template('manifold.html', cat_message=cat_messages["Manifold"])

@app.route('/blobs')
def blobs():
    return render_template('blobs.html', cat_message=cat_messages["Blobs"]) 

@app.route('/d20')
def d20():
    return render_template('d20.html', cat_message=cat_messages["D20"])

# =========== E-COMMERCE =========== 
@app.route("/jewelry") # E-COMMERCE EXPERIENCE
def jewelry():
    return render_template("jewelry.html", cat_message=cat_messages["Jewelry"])

@app.route("/art") # ART PAGE (CURRENTLY NOT IN MENU)
def art():
    return render_template("art.html", cat_message=cat_messages["Art"])

@app.route("/add_to_cart", methods=["POST"]) # ADD ITEM TO CART
def add_to_cart():
    item_name = request.form.get("item_name")
    item_price = float(request.form.get("item_price"))
    item_image = request.form.get("item_image")
    
    if not CheckAvailability(item_name): # MAKE SURE ITEM IS AVAILABLE ( FOR JEWELRY)
        # TODO: SHOW ERROR MESSAGE TO USER
        print(f"⚠️ Item {item_name} is no longer available")
        return redirect(request.referrer)
    
    if 'cart' not in session:
        session['cart'] = []
    
    session['cart'].append({
        'name': item_name,
        'price': item_price,
        'image': item_image
    })
    session.modified = True
    
    return redirect(request.referrer)

@app.route("/cart") # VIEW CART
def cart():
    cart_items = session.get('cart', [])
    total = sum(item['price'] for item in cart_items)
    return render_template("cart.html", cart_items=cart_items, total=total, cat_message=cat_messages["Cart"])

@app.route("/remove_from_cart/<int:index>")
def remove_from_cart(index):
    if 'cart' in session and 0 <= index < len(session['cart']):
        session['cart'].pop(index)
        session.modified = True
    return redirect(url_for('cart'))

@app.route("/checkout", methods=["GET", "POST"]) # CHECKOUT
def checkout():
    cart_items = session.get('cart', [])
    if not cart_items:
        return redirect(url_for('cart'))
    
    total = sum(item['price'] for item in cart_items)
    
    if request.method == "POST":
        real_purchase = request.form.get('real_purchase') == 'yes'
        
        order_data = {
            'name': request.form.get('name'),
            'email': request.form.get('email'),
            'phone': request.form.get('phone'),
            'address': request.form.get('address'),
            'city': request.form.get('city'),
            'state': request.form.get('state'),
            'zip': request.form.get('zip'),
            'total': total,
            'real_purchase': real_purchase,
            'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        
        order_number = NewOrder(order_data, cart_items) #SAVE TO POSTGRESQL
        
        if order_number: # ADD ORDER NUMBER TO EMAIL
            order_data['order_number'] = order_number 
            order_data['items'] = cart_items
            
            OrderEmailAsync(order_data) # SEND EMAIL
            
            session['cart'] = [] # CLEAR CART
            session.modified = True
            
            return redirect(url_for('order_confirmation'))
        else:
            return "Error creating order", 500
    
    return render_template("checkout.html", cart_items=cart_items, total=total, cat_message=cat_messages["Checkout"])

@app.route("/order_confirmation") # ORDER CONFIRMATION
def order_confirmation():
    return render_template("order_confirmation.html", cat_message=cat_messages["OrderConfirmation"])

# =========== DEMO DASHBOARD ===========
@app.route("/demo/admin")
def demo_admin_dashboard(): # PUBLIC DEMO - NO LOGIN REQUIRED
    if 'demo_orders' not in session: # GENERATE ORDERS ONCE AND STORE IN SESSION
        session['demo_orders'] = get_demo_orders()
    
    orders = session['demo_orders']
    stats = get_demo_stats(orders)
    return render_template("demo_admin_dashboard.html", stats=stats, demo_mode=True, cat_message=cat_messages["DemoDashboard"])

@app.route("/demo/admin/orders") 
def demo_admin_orders(): # DEMO VERSION OF ORDERS PAGE
    if 'demo_orders' not in session: # USE STORED ORDERS FROM SESSION
        session['demo_orders'] = get_demo_orders()
    
    orders = session['demo_orders']
    
    if 'demo_updates' in session: # APPLY ANY STATUS UPDATES FROM SESSION
        for order in orders:
            status_key = f'order_{order["order_id"]}_status'
            tracking_key = f'order_{order["order_id"]}_tracking'
            carrier_key = f'order_{order["order_id"]}_carrier'
            
            if status_key in session['demo_updates']:
                order['order_status'] = session['demo_updates'][status_key]
            if tracking_key in session['demo_updates']:
                order['tracking_number'] = session['demo_updates'][tracking_key]
            if carrier_key in session['demo_updates']:
                order['shipping_carrier'] = session['demo_updates'][carrier_key]
    
    filter_status = request.args.get('filter_status') # FILTER BY STATUS
    if filter_status:
        orders = [o for o in orders if o['order_status'] == filter_status]
    
    incomplete_count = sum(1 for o in orders if o['order_status'] != 'completed')
    return render_template("demo_admin_orders.html", 
                         orders=orders, 
                         incomplete_count=incomplete_count,
                         filter_status=filter_status,
                         demo_mode=True,
                         cat_message=cat_messages["DemoOrders"])

@app.route("/demo/admin/orders/search", methods=["POST"]) # DEMO ADMIN ORDERS SEARCH
def demo_admin_orders_search():
    search_term = request.form.get("search_term", "").strip().lower()
    
    if 'demo_orders' not in session: # USED STORED ORDERS FROM SESSION
        session['demo_orders'] = get_demo_orders()
    
    all_orders = session['demo_orders']
    
    if 'demo_updates' in session:
        for order in all_orders:
            status_key = f'order_{order["order_id"]}_status'
            tracking_key = f'order_{order["order_id"]}_tracking'
            carrier_key = f'order_{order["order_id"]}_carrier'
            
            if status_key in session['demo_updates']:
                order['order_status'] = session['demo_updates'][status_key]
            if tracking_key in session['demo_updates']:
                order['tracking_number'] = session['demo_updates'][tracking_key]
            if carrier_key in session['demo_updates']:
                order['shipping_carrier'] = session['demo_updates'][carrier_key]
    
    if search_term: # FILTER ORDERS BY SEARCH TERM
        orders = [o for o in all_orders 
                 if search_term in o['order_number'].lower() 
                 or search_term in o['customer_email'].lower()]
    else:
        orders = all_orders
    
    incomplete_count = sum(1 for o in orders if o['order_status'] != 'completed')
    return render_template("demo_admin_orders.html", 
                         orders=orders, 
                         incomplete_count=incomplete_count,
                         search_term=search_term,
                         demo_mode=True)

@app.route("/demo/admin/order/update-status/<int:order_id>/<status>", methods=["POST"])
def demo_update_order_status(order_id, status): # DEMO ORDER STATUS UPDATE
    if 'demo_updates' not in session:
        session['demo_updates'] = {}
    session['demo_updates'][f'order_{order_id}_status'] = status
    session.modified = True
    
    return redirect(url_for('demo_admin_orders'))

@app.route("/demo/admin/order/update-tracking/<int:order_id>", methods=["POST"])
def demo_update_tracking(order_id): # DEMO TRACKING UPDATE
    tracking_number = request.form.get("tracking_number", "")
    carrier = request.form.get("carrier", "")
    
    if 'demo_updates' not in session:
        session['demo_updates'] = {}
    session['demo_updates'][f'order_{order_id}_tracking'] = tracking_number
    session['demo_updates'][f'order_{order_id}_carrier'] = carrier
    session.modified = True
    
    return redirect(url_for('demo_admin_orders'))

@app.route("/demo/admin/contacts") # FAKE MESSAGES FOR DEMO
def demo_admin_contacts():
    """Demo contacts page"""
    if 'demo_contacts' not in session:
        session['demo_contacts'] = get_demo_contacts()
    
    contacts = session['demo_contacts']
    unread_count = sum(1 for c in contacts if c.get('status') == 'unread')
    return render_template("demo_admin_contacts.html", 
                         contacts=contacts, 
                         unread_count=unread_count,
                         demo_mode=True,
                         cat_message=cat_messages["DemoContacts"])

@app.route("/demo/admin/contact/update-status/<int:submission_id>/<status>", methods=["POST"])
def demo_update_contact_submission_status(submission_id, status): # DEMO CONTACT MESSAGE STATUS UPDATES - SHOWS CHANGE BUT DOESN'T UPDATE DATABASE
    if 'demo_contacts' not in session: # GET CONTACT MESSAGES FROM SESSION
        session['demo_contacts'] = get_demo_contacts()
    
    contacts = session['demo_contacts'] # UPDATE STATUS IN SESSION
    for contact in contacts:
        if contact['submission_id'] == submission_id:
            contact['status'] = status
            break
    
    session['demo_contacts'] = contacts
    session.modified = True
    
    return redirect(url_for('demo_admin_contacts'))

@app.route("/demo/admin/suggestions") # FAKE SUGGESTIONS BOX FOR DEMO
def demo_admin_suggestions():
    if 'demo_suggestions' not in session:
        session['demo_suggestions'] = get_demo_suggestions()
    
    suggestions = session['demo_suggestions']
    unread_count = sum(1 for s in suggestions if s.get('status', 'unread') == 'unread')
    return render_template("demo_admin_suggestions.html", 
                         suggestions=suggestions, 
                         unread_count=unread_count,
                         demo_mode=True, cat_message=cat_messages["DemoSuggestions"])

@app.route("/demo/admin/suggestion/update-status/<int:suggestion_id>/<status>", methods=["POST"])
def demo_update_suggestion_status(suggestion_id, status): # DEMO SUGGESTION STATUS UPDATE - SHOWS CHANGE BUT DOESN'T SAVE TO DATABASE
    if 'demo_suggestions' not in session: # GET SUGGESTIONS FROM SESSION
        session['demo_suggestions'] = get_demo_suggestions()
    
    suggestions = session['demo_suggestions'] # UPDATE STATUS IN SESSION
    for suggestion in suggestions:
        if suggestion['suggestion_id'] == suggestion_id:
            suggestion['status'] = status
            break
    
    session['demo_suggestions'] = suggestions
    session.modified = True
    
    return redirect(url_for('demo_admin_suggestions'))

@app.route("/demo/admin/reset") # RESET DEMO DATA
def demo_reset():
    """Reset all demo data"""
    session.pop('demo_orders', None)
    session.pop('demo_updates', None)
    session.pop('demo_contacts', None)
    session.pop('demo_suggestions', None)
    return redirect(url_for('demo_admin_dashboard'))


# ============================================  CONNECT AND COLLAB  ============================================
@app.route("/contact", methods=["GET", "POST"]) # SEND ME A MESSAGE
def contact():
    if request.method == "POST":
        NewRequest = {
            "HumanName": request.form.get("HumanName"),
            "EmailAddy": request.form.get("EmailAddy"),
            "Request": request.form.get("Request"),
            "ProductRequest": request.form.get("ProductRequest", ""),
            "AppRequest": request.form.get("AppRequest", ""),
            "message": request.form.get("message"),
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        
        if NewContactSubmission(NewRequest):
            EmailAsync(NewRequest)
            return redirect(url_for("contact", success=True))
        else:
            return "Error saving contact submission", 500
    
    success = request.args.get("success", False)
    return render_template("contact.html", success=success, cat_message=cat_messages["ContactMe"])

@app.route("/suggestions", methods=["GET", "POST"]) # SUGGESTIONS BOX PAGE
def suggestions():
    if request.method == "POST":
        new_suggestion = {
            "name": request.form.get("name", "Anonymous"),
            "email": request.form.get("email", ""),
            "suggestion_type": request.form.get("suggestion_type"),
            "suggestion": request.form.get("suggestion")
        }
        
        if NewSuggestion(new_suggestion):
            return redirect(url_for("suggestions", success=True))
        else:
            return "Error saving suggestion", 500

    success = request.args.get("success", False)
    return render_template("suggestions.html", success=success, cat_message=cat_messages["SuggestionsBox"])

@app.route('/admin/suggestions/<int:suggestion_id>/status', methods=['POST']) # SUGGESTIONS BOX - STATUS UPDATE FOR ADMIN DASHBOARD
def update_suggestion_status(suggestion_id):
    if 'admin_logged_in' not in session:
        return redirect(url_for('admin_login'))
    
    status = request.form.get('status')
    
    try:
        update_suggestion_status_db(suggestion_id, status)
        flash(f'Suggestion marked as {status}!', 'success')
    except Exception as e:
        flash(f'Error updating suggestion: {str(e)}', 'error')
    
    return redirect(url_for('admin_suggestions'))

@app.route('/request', methods=['GET', 'POST']) # APP OR WEBSITE REQUEST PAGE
def request_app():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        phone = request.form.get('phone')
        request_type = request.form.get('request_type')
        timeline = request.form.get('timeline')
        budget = request.form.get('budget')
        additional_info = request.form.get('additional_info')
        
        try:
            submit_app_request(name, email, phone, request_type, timeline, budget, additional_info)
            return render_template('request.html', success=True)
        except Exception as e:
            flash(f'Error submitting request: {str(e)}', 'error')
            return render_template('request.html', success=False)
    
    return render_template('request.html', success=False, cat_message=cat_messages["AppRequests"])

@app.route("/partnerships", methods=["GET", "POST"], ) # PARTNERSHIP PAGE
def partnerships():
    if request.method == "POST":
        new_inquiry = {
            "business_name": request.form.get("business_name"),
            "contact_name": request.form.get("contact_name"),
            "contact_email": request.form.get("contact_email"),
            "contact_phone": request.form.get("contact_phone"),
            "business_type": request.form.get("business_type"),
            "market_locations": request.form.get("market_locations"),
            "interest_type": request.form.get("interest_type"),
            "estimated_quantity": request.form.get("estimated_quantity"),
            "additional_info": request.form.get("additional_info")
        }
        
        if add_partnership_inquiry(new_inquiry): #SEND EMAIL NOTIFICATION
            # TODO: Send email notification
            return redirect(url_for("partnerships", success=True))
        else:
            return "Error saving partnership inquiry", 500
    
    success = request.args.get("success", False)
    return render_template("partnerships.html", success=success, cat_message=cat_messages["Partner"])


# ============================================  REAL ADMIN PAGES - PW REQUIRED ============================================
@app.route("/admin/login", methods=["GET", "POST"])
def admin_login(): # LOG INTO ADMIN DASHBOARD
    if request.method == "POST":
        password = request.form.get("password")
        if password == ADMIN_PASSWORD:
            session['admin_logged_in'] = True
            return redirect(url_for('admin_dashboard'))
        else:
            return render_template("admin_login.html", error="Invalid password")
    
    return render_template("admin_login.html")

@app.route("/admin/logout")
def admin_logout(): # ADMIN LOG OUT
    session.pop('admin_logged_in', None)
    return redirect(url_for('home'))

@app.route("/admin")
@AdminRequired
def admin_dashboard(): # MAIN ADMIN DASHBOARD WITH OVERVIEW   
    # GET DATA
    contacts = GetContactSubmissions()
    suggestions = GetSuggestions()
    orders = GetOrders()
    real_orders = GetRealOrders()
    partners = get_all_partnership_inquiries()
    
    unread_contacts = sum(1 for c in contacts if c.get('status') == 'unread') # COUND UNREAD CONTACTS
    
    pending_orders = sum(1 for o in orders if o.get('order_status') != 'completed') # COUNT ALL PENDING ORDERS (NOT COMPLETE)
    
    pending_real_purchases = sum(1 for o in real_orders if o.get('order_status') != 'completed') # COUNT PENDING REAL PURCHASES (REAL PURCHASE + NOT COMPLETE)
    
    stats = {
        'unread_contacts': unread_contacts,
        'total_suggestions': len(suggestions),
        'pending_orders': pending_orders,
        'pending_real_purchases': pending_real_purchases,
        'total_partners': len(partners),
        'recent_contacts': contacts[:5],
        'recent_orders': orders[:10],  # SHOW RECENT ORDERS (ALL TYPES)
        'recent_partners': partners[:5]
    }
    
    # In your admin_dashboard route, add these lines:
    request_stats = get_app_request_stats()
    stats['new_app_requests'] = request_stats['new_requests']
    stats['recent_app_requests'] = request_stats['recent_requests']

    return render_template("admin_dashboard.html", stats=stats, cat_message=cat_messages["AdminDashboard"])

# ===== MESSAGES AND SUGGESTIONS =====
@app.route('/admin/messages-suggestions') # COMBINED MESSAGES AND SUGGESTIONS
def admin_messages_suggestions():
    if 'admin_logged_in' not in session:
        return redirect(url_for('admin_login'))
    
    try:
        # Get contacts
        contacts = GetContactSubmissions()
        unread_contacts = sum(1 for c in contacts if c['status'] == 'unread')
        
        # Get suggestions
        suggestions = GetSuggestions()
        unread_suggestions = sum(1 for s in suggestions if s.get('status') != 'read' and not s.get('archived') and not s.get('added_to_wishlist'))
        
        return render_template('admin_messages_suggestions.html', 
                             contacts=contacts, 
                             suggestions=suggestions,
                             unread_contacts=unread_contacts,
                             unread_suggestions=unread_suggestions)
    except Exception as e:
        flash(f'Error loading data: {str(e)}', 'error')
        return redirect(url_for('admin_messages_suggestions'))

@app.route("/admin/contact/update-status/<int:submission_id>/<status>", methods=["POST"])
@AdminRequired
def update_contact_submission_status(submission_id, status): #UPDATE CONTACT SUBMISSION STATUS
    if update_contact_status(submission_id, status):
        return redirect(url_for('admin_contacts'))
    else:
        return "Error updating status", 500

@app.route('/admin/suggestions/<int:suggestion_id>/archive', methods=['POST']) # SUGGESTIONS BOX - ARCHIVE FOR ADMIN DASHBOARD
def archive_suggestion(suggestion_id):
    if 'admin_logged_in' not in session:
        return redirect(url_for('admin_login'))
    
    try:
        archive_suggestion_db(suggestion_id)
        flash('Suggestion archived successfully!', 'success')
    except Exception as e:
        flash(f'Error archiving suggestion: {str(e)}', 'error')
    
    return redirect(url_for('admin_suggestions'))

@app.route('/admin/suggestions/<int:suggestion_id>/add-to-wishlist', methods=['POST']) # SUGGESTIONS BOX - WISHLIST FOR ADMIN DASHBOARD
def add_suggestion_to_wishlist_route(suggestion_id):
    if 'admin_logged_in' not in session:
        return redirect(url_for('admin_login'))
    
    try:
        success = add_suggestion_to_wishlist_db(suggestion_id)
        if success:
            flash('Suggestion added to wishlist!', 'success')
        else:
            flash('Suggestion not found!', 'error')
    except Exception as e:
        flash(f'Error adding to wishlist: {str(e)}', 'error')
    
    return redirect(url_for('admin_suggestions'))

# ===== APP REQUESTS =====
@app.route('/admin/app_requests') 
def admin_app_requests():
    if 'admin_logged_in' not in session:
        return redirect(url_for('admin_login'))
    
    filter_status = request.args.get('filter_status')
    
    try:
        all_requests = get_all_app_requests()
        
        # Filter if needed
        if filter_status:
            requests = [r for r in all_requests if r['status'] == filter_status]
        else:
            requests = all_requests
        
        # Get counts
        all_count = len(all_requests)
        new_count = sum(1 for r in all_requests if r['status'] == 'new')
        contacted_count = sum(1 for r in all_requests if r['status'] == 'contacted')
        in_progress_count = sum(1 for r in all_requests if r['status'] == 'in_progress')
        completed_count = sum(1 for r in all_requests if r['status'] == 'completed')
        
        return render_template('admin_app_requests.html',
                             requests=requests,
                             filter_status=filter_status,
                             all_count=all_count,
                             new_count=new_count,
                             contacted_count=contacted_count,
                             in_progress_count=in_progress_count,
                             completed_count=completed_count)
    except Exception as e:
        flash(f'Error loading requests: {str(e)}', 'error')
        return redirect(url_for('admin_app_requests'))

@app.route('/admin/app_requests/<int:request_id>/status', methods=['POST'])
def update_request_status_route(request_id):
    if 'admin_logged_in' not in session:
        return redirect(url_for('admin_login'))
    
    status = request.form.get('status')
    
    try:
        update_app_request_status(request_id, status)
        flash('Request status updated!', 'success')
    except Exception as e:
        flash(f'Error updating status: {str(e)}', 'error')
    
    return redirect(url_for('admin_app_requests'))

@app.route('/admin/app_requests/<int:request_id>/notes', methods=['POST'])
def update_request_notes_route(request_id):
    if 'admin_logged_in' not in session:
        return redirect(url_for('admin_login'))
    
    notes = request.form.get('notes')
    
    try:
        update_app_request_notes(request_id, notes)
        flash('Notes updated!', 'success')
    except Exception as e:
        flash(f'Error updating notes: {str(e)}', 'error')
    
    return redirect(url_for('admin_app_requests'))

@app.route('/admin/requests/<int:request_id>/archive', methods=['POST'])
def archive_app_request(request_id):
    if 'admin_logged_in' not in session:
        return redirect(url_for('admin_login'))
    
    try:
        archive_app_request_db(request_id)
        flash('Request archived successfully!', 'success')
    except Exception as e:
        flash(f'Error archiving request: {str(e)}', 'error')
    
    return redirect(url_for('admin_app_requests'))

# ==== PARTNER  ====
@app.route("/admin/partners")
@AdminRequired
def admin_partners(): # PARTNERSHIP INQUIRIES
    """View all partnership inquiries"""
    partners = get_all_partnership_inquiries()
    new_count = sum(1 for p in partners if p.get('status') == 'new')
    return render_template("admin_partners.html", partners=partners, new_count=new_count, cat_message=cat_messages["AdminPartners"])

@app.route("/admin/partnership/update-status/<int:inquiry_id>/<status>", methods=["POST"]) 
@AdminRequired
def update_partnership_status_route(inquiry_id, status): # UPDATE PARTNERSHIP INQUIRY STATUS
    if update_partnership_status(inquiry_id, status):
        return redirect(url_for('admin_partners'))
    else:
        return "Error updating status", 500

# ==== ORDERS ====
@app.route('/admin/orders')
def admin_orders():
    print("=== ADMIN ORDERS ROUTE STARTED ===")
    
    if 'admin_logged_in' not in session:
        print("Not logged in, redirecting...")
        return redirect(url_for('admin_login'))
    
    print("Session check passed")
    filter_status = request.args.get('filter_status')
    print(f"Filter status: {filter_status}")
    
    try:
        print("Fetching all orders...")
        all_orders = GetOrders()
        print(f"Got {len(all_orders)} orders")
        
        # Apply filter if specified
        if filter_status:
            orders = [order for order in all_orders if order['order_status'] == filter_status]
            print(f"Filtered to {len(orders)} orders")
        else:
            orders = all_orders
        
        incomplete_count = sum(1 for order in all_orders 
                             if order['order_status'] not in ['demo', 'completed'])
        
        print(f"Rendering template with {len(orders)} orders")
        return render_template('admin_orders.html', 
                             orders=orders,
                             incomplete_count=incomplete_count,
                             filter_status=filter_status,
                             search_term=None)
    except Exception as e:
        print(f"ERROR: {str(e)}")
        import traceback
        traceback.print_exc()
        flash(f'Error loading orders: {str(e)}', 'error')
        return redirect(url_for('admin_dashboard'))

@app.route("/admin/real-purchases")
@AdminRequired
def admin_real_purchases(): # VIEW REAL ORDERS ONLY
    real_orders = GetRealOrders()
    incomplete_count = sum(1 for o in real_orders if o.get('order_status') != 'completed')
    return render_template("admin_real_purchases.html", orders=real_orders, incomplete_count=incomplete_count)

@app.route("/admin/order/update-status/<int:order_id>/<status>", methods=["POST"])
@AdminRequired
def update_order_status_route(order_id, status): # UPDATE ORDER STATUS
    if update_order_status(order_id, status):
        return redirect(request.referrer or url_for('admin_orders')) # REDIRECT BAC TO REFERRING PAGE
    else:
        return "Error updating status", 500

@app.route("/admin/orders/search", methods=["GET", "POST"])
@AdminRequired
def admin_orders_search(): # SEARCH ORDERS
    """Search orders by order number or email"""
    if request.method == "POST":
        search_term = request.form.get("search_term", "").strip()
        if search_term:
            orders = search_orders(search_term)
            incomplete_count = sum(1 for o in orders if o.get('order_status') != 'completed')
            return render_template("admin_orders.html", 
                                 orders=orders, 
                                 incomplete_count=incomplete_count,
                                 search_term=search_term)
    
    # If GET or no search term, redirect to regular orders page
    return redirect(url_for('admin_orders'))

@app.route("/admin/order/update-tracking/<int:order_id>", methods=["POST"])
@AdminRequired
def update_tracking(order_id): # UPDATE TRACKING NUMBER
    """Update tracking number for an order"""
    tracking_number = request.form.get("tracking_number", "").strip()
    carrier = request.form.get("carrier", "").strip()
    
    if update_order_tracking(order_id, tracking_number, carrier):
        # Auto-update status to shipped if tracking is added
        if tracking_number and tracking_number != "":
            update_order_status(order_id, 'shipped')
    
    return redirect(request.referrer or url_for('admin_orders'))

@app.route('/admin/orders/<int:order_id>/archive', methods=['POST'])
def archive_order(order_id):
    if 'admin_logged_in' not in session:
        return redirect(url_for('admin_login'))
    
    try:
        archive_order_db(order_id)
        flash('Order archived successfully!', 'success')
    except Exception as e:
        flash(f'Error archiving order: {str(e)}', 'error')
    
    return redirect(url_for('admin_orders'))

#======= WISHLIST ======
@app.route("/admin/wishlist")
@AdminRequired
def admin_wishlist():
    """View wishlist of future enhancements"""
    filter_status = request.args.get('filter_status')
    
    # Get all wishlist items (filtered or not)
    wishlist_items = GetWishlist(filter_status)
    
    # Get counts for each status
    all_items = GetWishlist()  # Get all for counting
    all_count = len(all_items)
    not_started_count = sum(1 for item in all_items if item['status'] == 'not_started')
    in_progress_count = sum(1 for item in all_items if item['status'] == 'in_progress')
    completed_count = sum(1 for item in all_items if item['status'] == 'completed')
    revisiting_count = sum(1 for item in all_items if item['status'] == 'revisiting')
    
    return render_template("admin_wishlist.html", 
                         wishlist_items=wishlist_items,
                         filter_status=filter_status,
                         all_count=all_count,
                         not_started_count=not_started_count,
                         in_progress_count=in_progress_count,
                         completed_count=completed_count,
                         revisiting_count=revisiting_count,
                         cat_message=cat_messages["AdminWishlist"])

@app.route("/admin/wishlist/add", methods=["POST"])
@AdminRequired
def add_wishlist_item_route():
    """Add a new item to wishlist"""
    new_item = {
        'source': request.form.get('source', 'Me'),
        'enhancement_type': request.form.get('enhancement_type'),
        'details': request.form.get('details'),
        'status': 'not_started',
        'notes': request.form.get('notes', '')
    }
    
    if NewWishlistItem(new_item):
        return redirect(url_for('admin_wishlist'))
    else:
        return "Error adding wishlist item", 500

@app.route("/admin/wishlist/update-status/<int:wishlist_id>/<status>", methods=["POST"])
@AdminRequired
def update_wishlist_status_route(wishlist_id, status):
    """Update status of a wishlist item"""
    if update_wishlist_status(wishlist_id, status):
        return redirect(request.referrer or url_for('admin_wishlist'))
    else:
        return "Error updating status", 500

@app.route("/admin/wishlist/update-notes/<int:wishlist_id>", methods=["POST"])
@AdminRequired
def update_wishlist_notes_route(wishlist_id):
    """Update notes for a wishlist item"""
    notes = request.form.get('notes', '')
    
    if update_wishlist_notes(wishlist_id, notes):
        return redirect(request.referrer or url_for('admin_wishlist'))
    else:
        return "Error updating notes", 500

@app.route('/admin/wishlist/<int:wishlist_id>/archive', methods=['POST'])
def archive_wishlist_item(wishlist_id):
    if 'admin_logged_in' not in session:
        return redirect(url_for('admin_login'))
    
    try:
        archive_wishlist_item_db(wishlist_id)
        flash('Wishlist item archived successfully!', 'success')
    except Exception as e:
        flash(f'Error archiving item: {str(e)}', 'error')
    
    return redirect(url_for('admin_wishlist'))

@app.route('/admin/wishlist/<int:wishlist_id>/delete', methods=['POST'])
def delete_wishlist_item(wishlist_id):
    if 'admin_logged_in' not in session:
        return redirect(url_for('admin_login'))
    
    try:
        delete_wishlist_item_db(wishlist_id)
        flash('Wishlist item permanently deleted!', 'success')
    except Exception as e:
        flash(f'Error deleting item: {str(e)}', 'error')
    
    return redirect(url_for('admin_wishlist'))

#======= LEGACY - CURRENTLY NOT IN USE  ======
@app.route("/admin/suggestions") # LEGACY / CURRENTLY NOT IN USE
@AdminRequired
def admin_suggestions(): # VIEW ALL SUGGESTIONS
    suggestions = GetSuggestions()
    unread_count = sum(1 for s in suggestions if s.get('status', 'unread') == 'unread')
    return render_template("admin_suggestions.html", suggestions=suggestions, unread_count=unread_count)

@app.route("/admin/contacts") # LEGACY - CURRENTLY NOT IN USE
@AdminRequired
def admin_contacts(): # VIEW ALL CONTACT SUBMISSIONS
    contacts = GetContactSubmissions()
    unread_count = sum(1 for c in contacts if c.get('status') == 'unread')
    return render_template("admin_contacts.html", contacts=contacts, unread_count=unread_count, cat_message=cat_messages["AdminContacts"])

# ============================================ TESTS ============================================
@app.route('/test') 
def test():
    return render_template('test.html')

@app.route("/circuitboard")
def circuitboard():
    return render_template("circuitboard.html")

# ============================================ MAIN ============================================
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port, debug=True)